### ISSUE TITLE
Updated Documentation on ReadTheDocs for Config Files

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#11]
The '-c' and '-e' positional arguments described in Configuration fields on ReadTheDocs do not exist. Inputting "config-nspyre -h" in the nspyre environment produces this terminal window. 

![image](https://user-images.githubusercontent.com/47992941/95362514-0acee000-0883-11eb-9320-60266cfc8589.png)

This might just be a problem with the documentation, since there seems to be a way to add a configuration file with -a. I am also having a problem with writing down the path to my new configuration file. Should I start from my C:/ drive? And does it need to be in the same folder as the default configuration files? Thanks

**Comment by jacobfeder** [comment]
You are correct that the documentation is just out of date. Configs are now added with -a and listed with -l. If you want you are welcome to update the docs, otherwise we will get to it soon.

The paths can be absolute or relative and are stored using Path(<yourpath>).resolve()
https://docs.python.org/3/library/pathlib.html
